// <auto-generated />
namespace Model.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.0.0-20911")]
    public sealed partial class add_ispublic : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(add_ispublic));
        
        string IMigrationMetadata.Id
        {
            get { return "202303030749204_add_ispublic"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
