//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebApplication2.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class CHUYENMUC
    {
        public int IDCM { get; set; }
        public Nullable<int> IDCMCha { get; set; }
        public string TenCM { get; set; }
        public string Link { get; set; }
    }
}
