'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated from a template.
'
'     Manual changes to this file may cause unexpected behavior in your application.
'     Manual changes to this file will be overwritten if the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Imports System
Imports System.Collections.Generic

Namespace WebApplication1

    Partial Public Class BAIDANG
        Public Property IDBaiDang As Integer
        Public Property TenBaiDang As String
        Public Property TieuDe As String
        Public Property UrlRequire As String
        Public Property AnhDaiDien As String
        Public Property NoiDung As String
        Public Property IDTaiKhoan As Integer
        Public Property NgayDang As Nullable(Of Date)
        Public Property TrangThaiBaiDang As String
        Public Property IDTheLoai As Integer
    
        Public Overridable Property TAIKHOAN As TAIKHOAN
        Public Overridable Property THELOAI As THELOAI
        Public Overridable Property LUOTXEMs As ICollection(Of LUOTXEM) = New HashSet(Of LUOTXEM)
    
    End Class

End Namespace
