'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated from a template.
'
'     Manual changes to this file may cause unexpected behavior in your application.
'     Manual changes to this file will be overwritten if the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Imports System
Imports System.Collections.Generic

Namespace WebApplication1

    Partial Public Class CHUYENMUC
        Public Property IDCM As Integer
        Public Property IDCMCha As Nullable(Of Integer)
        Public Property TenCM As String
        Public Property Link As String
    
    End Class

End Namespace
