'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated from a template.
'
'     Manual changes to this file may cause unexpected behavior in your application.
'     Manual changes to this file will be overwritten if the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Imports System
Imports System.Collections.Generic

Namespace WebApplication1

    Partial Public Class LUOTXEM
        Public Property ID As Integer
        Public Property NgayThang As Date
        Public Property IDBaiDang As Integer
    
        Public Overridable Property BAIDANG As BAIDANG
    
    End Class

End Namespace
