'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated from a template.
'
'     Manual changes to this file may cause unexpected behavior in your application.
'     Manual changes to this file will be overwritten if the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Imports System
Imports System.Collections.Generic

Namespace WebApplication1

    Partial Public Class TAIKHOAN
        Public Property IDTaiKhoan As Integer
        Public Property TenTaiKhoan As String
        Public Property MatKhau As String
        Public Property HoTen As String
        Public Property NgaySinh As Nullable(Of Date)
        Public Property GioiTinh As String
        Public Property Email As String
        Public Property DiaChi As String
        Public Property SDT As String
        Public Property AnhDaiDien As String
        Public Property TrangThaiNguoiDung As String
        Public Property QuyenHan As String
    
        Public Overridable Property BAIDANGs As ICollection(Of BAIDANG) = New HashSet(Of BAIDANG)
    
    End Class

End Namespace
