'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated from a template.
'
'     Manual changes to this file may cause unexpected behavior in your application.
'     Manual changes to this file will be overwritten if the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Imports System
Imports System.Collections.Generic

Namespace WebApplication1

    Partial Public Class THELOAI
        Public Property IDTheLoai As Integer
        Public Property TenTheLoai As String
        Public Property UrlRequire As String
    
        Public Overridable Property BAIDANGs As ICollection(Of BAIDANG) = New HashSet(Of BAIDANG)
    
    End Class

End Namespace
